# Generated by Django 4.0.6 on 2022-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('is_archive', models.BooleanField(default=False, verbose_name='В архиве')),
                ('role', models.CharField(choices=[('Официант', 'Waiter'), ('Повар', 'Cook'), ('Водитель', 'Driver')], default='Официант', max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон')),
                ('birthday', models.DateField(verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
    ]
