# Generated by Django 4.0.6 on 2022-07-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_archive',
            new_name='isArchive',
        ),
    ]
